=== 18F/vote-gov/config/gulp/dates/dates_schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "title": "Voting and Registration Dates Schema",
    "description": "A schema for storing important voting related dates by state.",
    "id": "https://vote.gov/config/gulp/dates/dates_schema.json",
    "type": "object",

    "definitions": {
        "date": {
            "type": "object",
            "properties": {
                "date": { "type": "string" },
                "date_type": {
                    "type": "string",
                    "enum": [
                        "Absentee Ballot Request Deadline",
                        "Absentee Ballot Return Deadline",
                        "Absentee Ballot Online Deadline",
                        "Voter Registration Deadline",
                        "Voter Registration Deadline (In Person)",
                        "Voter Registration Deadline (By Mail)",
                        "Voter Registration Deadline (Online)",
                        "Early Voting/ In Person Absentee Voting",
                        "Presidential Preference Primary Election",
                        "Primary Election",
                        "Election",
                        "Special Election",
                        "Special General Election",
                        "Special Runoff Election",
                        "Primary Runoff Election",
                        "Runoff Election"
                    ]
                }
            }
        }
    },

    "properties": {
        "slug": { "type": "string" },
        "state_abbreviation": { "type": "string" },
        "title": { "type": "string" },
        "important_dates": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/date"
            }
        }
    }
}

=== 18F/vote-gov/config/gulp/dates/dates.json
{
    "state_abbreviation": "ak",
    "slug": "alaska",
    "title": "Alaska",
    "important_dates": [
        {
            "date": "09-01-2019",
            "date_type": "Voter Registration Deadline"
        },
        {
            "date": "09-16-2019",
            "date_type": "Absentee Ballot Request Deadline"
        },
        {
            "date": "09-23-2019",
            "date_type": "Absentee Ballot Return Deadline"
        },
        {
            "date": "09-23-2019 to 09-27-2019",
            "date_type": "Early Voting/ In Person Absentee Voting"
        },
        {
            "date": "10-01-2019",
            "date_type": "Election"
        }
    ]
}
